---
- name: Install node and npm
  hosts: 167.71.139.136
  tasks:
    - name: update apt repo and cache     # first step before installing anything else
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt: 
        pkg:
          - nodejs
          - npm

- name: Deploy nodejs app
  hosts: 167.71.139.136
  tasks:
    - name: unpack the nodejs tar file
      unarchive:            # copy over and extract the tar file
        src: /Users/ausman/ansible/nodejs-app/nodejs-app-1.0.0.tgz 
        dest: /root/                      # destination folder
    - name: Install dependencies   # npm install
      community.general.npm:
        path: /root/package  # location directory of package.json
    - name: Start application  # node /root/package/app/server.js
      command: node /root/package/app/server
      async: 1000    #to make node server.js run in the background, like node server.js &
      poll: 0
    - name: Ensure app is running!
      shell: ps aux | grep node  # similar to 'command', but less secure
      register: app_status   # result of module (the shell command in this case) 'registered' to app_status
    - debug: msg={{app_status.stdout_lines}} # print app_status, but only stdout_lines




