---
- name: Configure nginx web server
  hosts: webserver
  tasks:
  - name: uninstall nginx server
    apt:                        # apt module
      name: nginx=1.26.0-2ubuntu3.2
      state: absent
  - name: start nginx server
    service:                    # service module
      name: nginx
      state: stopped